-- BrowseByMetadata userpatch
-- 
-- Deleted, the version in this repo is not maintained. See git history for the old version if you're interested.
--
-- Newer versions of this patch can be found in the GitHub issue: https://github.com/koreader/koreader/issues/8472
